I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script
    k "hello there"
Exception: Sayer 'k' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script
    k "hello there"
  File "/Users/jossieyan/Desktop/renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/jossieyan/Desktop/renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'k' is not defined.

Darwin-21.5.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
ubc dating 1.0
Wed Jun 22 02:00:46 2022
